### ISSUE TITLE
NonSdkApiUsedViolation: Landroid/graphics/FontFamily;-><init>()V

### ISSUE THREAD

**Issue by DeweyReed** [DeweyReed/DigitalWatchView#1]
```
12-01 21:41:09.241: D/StrictMode(16667): StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/graphics/FontFamily;-><init>()V
12-01 21:41:09.241: D/StrictMode(16667): 	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
12-01 21:41:09.241: D/StrictMode(16667): 	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
12-01 21:41:09.241: D/StrictMode(16667): 	at java.lang.Class.getDeclaredConstructorInternal(Native Method)
12-01 21:41:09.241: D/StrictMode(16667): 	at java.lang.Class.getConstructor0(Class.java:2325)
12-01 21:41:09.241: D/StrictMode(16667): 	at java.lang.Class.getConstructor(Class.java:1725)
12-01 21:41:09.241: D/StrictMode(16667): 	at androidx.core.graphics.f.a(Unknown Source:3)
12-01 21:41:09.241: D/StrictMode(16667): 	at androidx.core.graphics.f.<init>(Unknown Source:8)
12-01 21:41:09.241: D/StrictMode(16667): 	at androidx.core.graphics.g.<init>(Unknown Source:0)
12-01 21:41:09.241: D/StrictMode(1666z7): 	at androidx.core.graphics.c.<clinit>(Unknown Source:8)
12-01 21:41:09.241: D/StrictMode(16667): 	at androidx.core.graphics.c.a(Unknown Source:0)
12-01 21:41:09.241: D/StrictMode(16667): 	at androidx.core.a.b.f.a(Unknown Source:37)
12-01 21:41:09.241: D/StrictMode(16667): 	at androidx.core.a.b.f.a(Unknown Source:15)
12-01 21:41:09.241: D/StrictMode(16667): 	at androidx.core.a.b.f.a(Unknown Source:19)
12-01 21:41:09.241: D/StrictMode(16667): 	at io.github.deweyreed.digitalwatchview.DigitalWatchView$b.a(Unknown Source:5)
12-01 21:41:09.241: D/StrictMode(16667): 	at io.github.deweyreed.digitalwatchview.DigitalWatchView$b.<init>(Unknown Source:34)
12-01 21:41:09.241: D/StrictMode(16667): 	at io.github.deweyreed.digitalwatchview.DigitalWatchView.<init>(Unknown Source:196)
12-01 21:41:09.241: D/StrictMode(16667): 	at io.github.deweyreed.digitalwatchview.DigitalWatchView.<init>(Unknown Source:12)
12-01 21:41:09.241: D/StrictMode(16667): 	at io.github.deweyreed.digitalwatchview.DigitalWatchView.<init>(Unknown Source:6)
12-01 21:41:09.241: D/StrictMode(16667): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
12-01 21:41:09.241: D/StrictMode(16667): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
12-01 21:41:09.241: D/StrictMode(16667): 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
```

**Comment by Aksx73** [comment]
I am having the same warning about using a custom font for the whole app.
If you got it fixed please let me know.
thank you.
